// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeXDgpiiY97wDWQVOaKUhnWmMsmGrb13E',
    appId: '1:645896172204:web:95742414117b9c7960a509',
    messagingSenderId: '645896172204',
    projectId: 'bitnotes-1311c',
    authDomain: 'bitnotes-1311c.firebaseapp.com',
    storageBucket: 'bitnotes-1311c.firebasestorage.app',
    measurementId: 'G-9CF0M6PFKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0aINloPoVHLs67QSdt98XGA8i4KrXKs',
    appId: '1:645896172204:android:3d00a582e8b49f9960a509',
    messagingSenderId: '645896172204',
    projectId: 'bitnotes-1311c',
    storageBucket: 'bitnotes-1311c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPRwhuyrSzeNsWlxWiF4Fe0_cWzxyq9c',
    appId: '1:645896172204:ios:57ff100a024889e660a509',
    messagingSenderId: '645896172204',
    projectId: 'bitnotes-1311c',
    storageBucket: 'bitnotes-1311c.firebasestorage.app',
    iosBundleId: 'com.example.bitnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPRwhuyrSzeNsWlxWiF4Fe0_cWzxyq9c',
    appId: '1:645896172204:ios:57ff100a024889e660a509',
    messagingSenderId: '645896172204',
    projectId: 'bitnotes-1311c',
    storageBucket: 'bitnotes-1311c.firebasestorage.app',
    iosBundleId: 'com.example.bitnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeXDgpiiY97wDWQVOaKUhnWmMsmGrb13E',
    appId: '1:645896172204:web:10eebf94bf30627e60a509',
    messagingSenderId: '645896172204',
    projectId: 'bitnotes-1311c',
    authDomain: 'bitnotes-1311c.firebaseapp.com',
    storageBucket: 'bitnotes-1311c.firebasestorage.app',
    measurementId: 'G-T43VED0724',
  );
}
